Repository zeitgeistpm/ui, pull requests merged in 2022-09, with the labels that each got.

#219 Statically render front page
  .env.example
  components/markets/TrendingMarketCard.tsx
  components/markets/TrendingMarkets.tsx
  layouts/DefaultLayout.tsx
  lib/constants.ts
  lib/gql/popular-categories.ts
  lib/gql/trending-markets.ts
  lib/stores/TradeSlipStore.ts
  pages/index.tsx
Labels: work in progress, review needed

#220 fix form validation when outcomes type changes
  components/create/OutcomesField.tsx
  pages/create.tsx
Labels: review needed

#195 makets list fixes
  components/markets/MarketTable.tsx
  components/markets/MarketsList.tsx
  lib/stores/MarketStore.ts
  lib/stores/MarketsStore.ts
  lib/stores/Store.ts
  lib/util/tx.ts
  next.config.js
  package.json
  pages/_app.tsx
  scripts/createDummyMarkets.ts
  yarn.lock
Labels: review needed

#224 Wallet connection issues
  components/account/AccountButton.tsx
  components/ui/TransactionButton.tsx
Labels: review needed

#240 Adjust tags
  components/create/TagChoices.tsx
  lib/gql/popular-categories.ts
Labels: review needed

#245 allow authority wallet proxy accounts to report
  components/outcomes/ReportBox.tsx
  components/outcomes/ScalarReportBox.tsx
  lib/stores/MarketStore.ts
  lib/stores/MarketsStore.ts
Labels: review needed

#229 update next + tailwind
  lib/constants.ts
  next-env.d.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  styles/index.css
  tailwind.config.js
  yarn.lock
Labels: review needed

#270 Show earned badges
  package.json
  pages/avatar/[address].tsx
  yarn.lock
Labels: enhancement

#293 Correctly quote price for exchange box buys
  components/exchange/ExchangeBox.tsx
  lib/stores/ExchangeStore.ts
Labels: review needed

#307 Update error handling for trade slip
  lib/util/tx.ts
Labels: review needed

#305 Fix incorrect scalar asset displayed on portfolio page
  lib/util/market.ts
  pages/settings.tsx
Labels: review needed

#308 Misc cosmetic changes
  components/drawer/RightDrawer.tsx
  components/markets/MarketTable.tsx
  pages/markets/[marketid].tsx
Labels: review needed

#310 Exclude smoldot-light and include analyze tool for next js
  next.config.js
  package.json
  yarn.lock
Labels: review needed

#312 Add google analytics and misc fixes
  lib/stores/ExchangeStore.ts
  pages/_document.tsx
  pages/index.tsx
Labels: review needed

#237 Display better report details
  components/markets/MarketTimer.tsx
  lib/stores/MarketStore.ts
  pages/markets/[marketid].tsx
Labels: review needed
