Repository zeitgeistpm/ui, pull requests merged in 2022-08, with the labels that each got.

#165 #141 - bump avatar packages with double wallet popup fix
  package.json
  yarn.lock
Labels: bug

#155 Implement carousel glitch on hover
  components/ui/Carousel.tsx
  components/ui/GlitchImage.tsx
  styles/index.css
Labels: enhancement

#168 Wallet selection improvements
  components/account/WalletSelect.tsx
  lib/stores/Store.ts
  lib/wallets/index.ts
  scripts/createDummyMarkets.ts
Labels: review needed

#171 Integrate styx pallet into avatar claim flow
  .vscode/settings.json
  lib/util/tx.ts
  package.json
  pages/avatar/[address].tsx
  public/avatar_preview.jpeg
  yarn.lock
Labels: proposed for sprint, work in progress, review needed

#181 Identity settings improvement
  lib/stores/Store.ts
  lib/stores/UserStore.ts
  lib/wallets/index.ts
  pages/settings.tsx
Labels: review needed

#186 #185 Fix issue with signing nft actions accept and equip.
  package.json
  pages/avatar/[address].tsx
  yarn.lock
Labels: work in progress

#187 #183 skip burn step when minting avatar for tarot holders
  package.json
  pages/avatar/[address].tsx
  public/icons/singular.svg
  yarn.lock
Labels: enhancement, review needed

#189 #188 checkbox value prop not respected
  components/ui/Checkbox.tsx
  package.json
  yarn.lock
Labels: bug

#193 Show correct inventory of badges for address on identity page
  package.json
  pages/avatar/[address].tsx
  yarn.lock
Labels: bug

#182 Fees selection and usage
  components/exchange/ExchangeBox.tsx
  components/liquidity/PoolFeesSelect.tsx
  components/liquidity/PoolSettings.tsx
  components/markets/MarketAddresses.tsx
  components/markets/MarketTable.tsx
  components/trade-slip/TradeSlipBox.tsx
  components/trade-slip/index.tsx
  components/ui/inputs.tsx
  lib/math.spec.ts
  lib/stores/ExchangeStore.ts
  lib/stores/Store.ts
  lib/stores/TradeSlipStore.ts
  lib/util/pool.ts
  pages/create.tsx
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
Labels: review needed

#198 Upgrade SDK to latest 0.7.4 + create market ipfs cluster pinning fail fix
  lib/stores/Store.ts
  package.json
  pages/create.tsx
  yarn.lock
Labels: enhancement, review needed

#201 Display cost breakdown
  components/liquidity/PoolSettings.tsx
  components/markets/MarketCostModal.tsx
  components/markets/TrendingMarketCard.tsx
  lib/stores/Store.ts
  lib/util/market.spec.ts
  lib/util/market.ts
  pages/create.tsx
Labels: review needed

#202 Safe url query parsing and prevent submit
  components/ui/TransactionButton.tsx
  lib/hooks/useMarketsUrlQuery.ts
  pages/create.tsx
Labels: bug

#203 Signal re-render of avatar in account selector on claim/mint
  components/account/AccountButton.tsx
  components/ui/Avatar.tsx
  layouts/launch/AppLaunchLayout.tsx
Labels: bug

#217 slippage percentage recreates transactions
  components/exchange/ExchangeBox.tsx
  lib/stores/TradeSlipStore.ts
Labels: review needed
