Repository zeitgeistpm/ui, pull requests merged in 2022-11, with the labels that each got.

#380 Fix pagination and market images (markets list)
  components/markets/MarketCard.tsx
  components/markets/MarketsList.tsx
Labels: review needed

#385 Handle empty additional fields
  lib/stores/UserStore.ts
Labels: review needed

#383 Manually scroll to top
  layouts/DefaultLayout.tsx
  lib/util/should-scroll.spec.ts
  lib/util/should-scroll.ts
  next.config.js
Labels: review needed

#391 Add missing undefined checks
  layouts/DefaultLayout.tsx
Labels: review needed

#375 Text editor
  components/ui/QuillEditor.tsx
  components/ui/QuillViewer.tsx
  package.json
  pages/create.tsx
  pages/markets/[marketid].tsx
  styles/index.css
  styles/quill.css
  yarn.lock
Labels: review needed

#218 #215 scalar date markets
  .yarnrc.yml
  components/create/OutcomesField.tsx
  components/markets/MarketCard.tsx
  components/markets/ScalarPriceRange.tsx
  components/ui/inputs.tsx
  lib/constants.ts
  lib/gql/markets-list.ts
  lib/gql/markets.ts
  lib/stores/MarketStore.ts
  lib/types/create-market.ts
  pages/avatar/[address].tsx
  pages/create.tsx
  pages/markets/[marketid].tsx
  pages/settings.tsx
  yarn.lock
Labels: s:blocked, review needed

#392 Market cards
  components/markets/market-card/index.tsx
  components/markets/market-card/overlay-categories.tsx
  components/markets/market-card/overlay.tsx
  pages/demos.tsx
  tailwind.config.js
Labels: review needed

#400 nextjs update and remove launch countdown
  .eslintignore
  .eslintrc.js
  components/account/PortfolioCard.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/MarketCard.tsx
  components/markets/TrendingMarketCard.tsx
  components/menu/MenuItem.tsx
  components/menu/MobileMenu.tsx
  components/menu/SubMenuItem.tsx
  components/ui/Footer.tsx
  layouts/launch/AppLaunchLayout.tsx
  layouts/launch/Footer.tsx
  layouts/launch/Logo.tsx
  layouts/launch/Parallax.tsx
  layouts/launch/gfx/avatars.png
  layouts/launch/gfx/avatars.svg
  layouts/launch/gfx/avatars.tsx
  layouts/launch/gfx/ball1.png
  layouts/launch/gfx/ball2.png
  layouts/launch/gfx/ball3.png
  layouts/launch/gfx/ball4.png
  layouts/launch/gfx/ball5.png
  layouts/launch/gfx/ball6.png
  layouts/launch/gfx/down_carret.png
  layouts/launch/gfx/glow_ball.png
  layouts/launch/gfx/rocket.png
  layouts/launch/gfx/rocket_ball.png
  layouts/launch/gfx/saturn.png
  layouts/launch/gfx/star.png
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/court/index.tsx
  pages/index.tsx
  pages/liquidity/[poolid].tsx
  yarn.lock
Labels: review needed

#402 Add now mandatory alt prop
  components/markets/market-card/index.tsx
Labels: review needed

#390 Selective SSG
  lib/gql/markets.ts
  pages/markets/[marketid].tsx
Labels: review needed

#404 Add config from vercel. Remove item that doesn't exist on vercel
  .env.example
  lib/constants.ts
Labels: review needed

#396 Market creation deadlines input + liquidity page using sdkv2
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  components/assets/AssetActionButtons/ReportButton.tsx
  components/create/MarketDeadlinesInput.tsx
  components/liquidity/LiquidityPoolsBox.tsx
  components/outcomes/ReportBox.tsx
  components/outcomes/ScalarReportBox.tsx
  components/ui/Table.tsx
  layouts/DefaultLayout.tsx
  lib/hooks/index.ts
  lib/hooks/queries/useChainTime.ts
  lib/hooks/queries/useMarketDeadlineConstants.ts
  lib/hooks/queries/useMarketStatusCount.ts
  lib/hooks/queries/usePools.ts
  lib/hooks/queries/useSaturatedPoolsIndex.ts
  lib/hooks/queries/useTotalLiquidity.ts
  lib/hooks/queries/useZtgInfo.ts
  lib/hooks/useIsOnScreen.ts
  lib/hooks/usePoolsUrlQuery.ts
  lib/hooks/useSdkv2.ts
  lib/stores/MarketStore.ts
  lib/stores/PoolsStore.ts
  lib/stores/Store.ts
  lib/types/index.ts
  lib/util/fetch-ztg-price.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/asset.tsx
  pages/avatar/[address].tsx
  pages/create.tsx
  pages/liquidity/index.tsx
  scripts/createDummyMarkets.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#408 Implement pool details page using sdkv2
  components/markets/BuyFullSetModal.tsx
  components/markets/FullSetButtons.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/SellFullSetModal.tsx
  components/ui/NotificationCenter.tsx
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useMarket.ts
  lib/hooks/queries/useMarketIsTradingEnabled.ts
  lib/hooks/queries/usePool.ts
  lib/hooks/queries/useSaturatedMarket.ts
  package.json
  pages/liquidity/[poolid].tsx
  yarn.lock
Labels: bug, enhancement, refactor, review needed

#434 Add buy and sell buttons and fetch required data
  components/markets/market-card/index.tsx
  components/markets/market-card/overlay-categories.tsx
  components/markets/market-card/overlay.tsx
  components/trade-slip/BuySellButtons.tsx
  lib/gql/featured-markets.ts
  lib/gql/trending-markets.ts
Labels: review needed

#433 fix markets list scroll restoration
  components/markets/MarketsList.tsx
  lib/util/should-scroll.ts
Labels: review needed

#440 Fix identity page not showing earned badges
  pages/avatar/[address].tsx
Labels: bug

#441 Remove theme switcher + add new colors
  components/drawer/LeftDrawer.tsx
  components/icons/ZeitgeistIcon.tsx
  components/menu/MenuItem.tsx
  components/menu/index.tsx
  lib/stores/NavigationStore.tsx
  lib/stores/Store.ts
  lib/stores/UserStore.ts
  tailwind.config.js
Labels: review needed

#446 Handle missing asset
  components/markets/MarketAssetDetails.tsx
  lib/util/should-scroll.spec.ts
  pages/portfolio/[address].tsx
Labels: review needed

#460 Adopt new market schema
  components/markets/MarketsList.tsx
  components/markets/market-card/index.tsx
  components/markets/market-card/overlay-categories.tsx
  lib/gql/featured-markets.ts
  lib/gql/markets.ts
  lib/gql/trending-markets.ts
  lib/hooks/queries/useMarketIsTradingEnabled.ts
  package.json
  pages/index.tsx
  pages/markets/[marketid].tsx
  yarn.lock
Labels: review needed

#470 Grace fix main
  pages/create.tsx
Labels: review needed

#468 Set grace period correctly
  pages/create.tsx
Labels: review needed

#458 Tweak carousel
  components/markets/MarketScroll.tsx
  components/markets/market-card/index.tsx
  pages/index.tsx
Labels: review needed

#461 Market card - collect outcome data
  components/markets/MarketsList.tsx
  components/markets/market-card/context.ts
  components/markets/market-card/index.tsx
  components/markets/market-card/overlay-categories.tsx
  components/markets/market-card/overlay.tsx
  lib/gql/featured-markets.ts
  lib/gql/markets-list/outcomes-for-markets.ts
  lib/gql/trending-markets.ts
  lib/hooks/queries/useMarkets.ts
  lib/hooks/queries/useSaturatedMarket.ts
  lib/stores/Store.ts
  lib/types/markets.ts
  lib/util/assets.ts
  package.json
  pages/index.tsx
  styles/index.css
  yarn.lock
Labels: review needed
