Repository zeitgeistpm/ui, pull requests merged in 2023-05, with the labels that each got.

#1134 Fix pool fees last input visual bug
  components/liquidity/PoolFeesSelect.tsx
Labels: review needed

#1130 Match new subsquid params
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/useTransactionHistory.ts
  package.json
  yarn.lock
Labels: review needed

#1127 Retain market list scroll
  components/markets/MarketsList.tsx
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/useMarketsUrlQuery.ts
  lib/types/market-filter.ts
  next.config.js
Labels: review needed

#1079 Promoted markets
  components/markets/MarketHeader.tsx
  components/markets/PromotionCallout.tsx
  components/ui/Modal.tsx
  lib/cms/get-promoted-markets.ts
  lib/state/promotions.ts
  pages/markets/[marketid].tsx
  styles/index.css
Labels: feature, review needed

#1132 Chevron arrow in account menu
  components/account/AccountButton.tsx
Labels: review needed

#1138 Show block reason. Refactor transaction button
  components/ui/FormTransactionButton.tsx
  components/ui/TransactionButton.tsx
  package.json
  yarn.lock
Labels: review needed

#1149 Wallet migration hotfix
  lib/state/wallet.ts
Labels: review needed

#1122 Mobile market filters
  components/markets/market-filter/ClearAllButton.tsx
  components/markets/market-filter/DropDownSelect.tsx
  components/markets/market-filter/MarketActiveFilters.tsx
  components/markets/market-filter/MarketFiltersCheckboxes.tsx
  components/markets/market-filter/MarketFiltersContainer.tsx
  components/markets/market-filter/MarketFiltersDropdowns.tsx
  components/markets/market-filter/MarketFiltersSort.tsx
  components/markets/market-filter/index.tsx
  components/markets/market-filter/mobile-dialog/FilterDetails.tsx
  components/markets/market-filter/mobile-dialog/FiltersList.tsx
  components/markets/market-filter/mobile-dialog/index.tsx
  lib/constants/index.ts
  lib/constants/market-filter.ts
Labels: review needed

#1169 fix reporting
  components/assets/AssetActionButtons/ReportButton.tsx
Labels: review needed

#1173 Client crash on manually entering higher than max buy/sell asset values.
  components/trade-form/index.tsx
Labels: bug, review needed

#1179 Fix: update resolution date query
  lib/gql/resolution-date.ts
Labels: review needed

#1172 #1039 liquidity dropdown
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/ManageLiquidityButton.tsx
  components/liquidity/MarketLiquiditySection.tsx
  components/liquidity/PoolTable.tsx
  components/markets/BuyFullSetForm.tsx
  components/markets/BuySellFullSetsButton.tsx
  components/markets/FullSetButtons.tsx
  components/markets/SellFullSetForm.tsx
  components/ui/inputs.tsx
  package.json
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
  yarn.lock
Labels: review needed

#1198 Detailed trade history
  components/portfolio/TradeHistoryTable.tsx
  components/portfolio/TransactionHistoryTable.tsx
  lib/hooks/queries/useTradeHistory.ts
  lib/hooks/queries/useTransactionHistory.ts
  package.json
  pages/portfolio/[address].tsx
  yarn.lock
Labels: review needed

#1126 Market history
  components/markets/MarketHeader.tsx
  lib/gql/markets.ts
  lib/gql/resolution-date.ts
  lib/hooks/queries/useMarketEventHistory.ts
  lib/hooks/queries/useTimeStampForBlock.ts
  lib/util/get-scalar-outcome.ts
  lib/util/market-status-details.ts
  pages/markets/[marketid].tsx
Labels: review needed

#1224 Always show yes prediction percentage
  components/markets/market-card/index.tsx
Labels: review needed

#1221 Chart adjustments
  components/markets/MarketChart.tsx
  components/ui/TimeSeriesChart.tsx
  pages/markets/[marketid].tsx
Labels: review needed

#1240 Adjust viewbox for account menu chevron
  components/account/AccountButton.tsx
Labels: review needed

#1237 Portfolio value denomination
  components/front-page/PopularCategories.tsx
  components/markets/MarketAssetDetails.tsx
  components/portfolio/BondsTable.tsx
  components/portfolio/MarketPositions.tsx
  e2e/index.spec.ts
  lib/hooks/queries/useAccountBonds.ts
  lib/hooks/queries/useAssetUsdPrice.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/util/lookup-price.ts
Labels: review needed

#1253 Add back scalar bounds to market page
  components/markets/MarketHeader.tsx
  lib/hooks/queries/usePoolLiquidity.ts
  pages/markets/[marketid].tsx
Labels: review needed

#1263 Restructure portfolio page
  components/avatar/BadgesList.tsx
  components/icons/DiscordIcon.tsx
  components/icons/TwitterIcon.tsx
  components/portfolio/Breakdown.tsx
  components/portfolio/HistoryTabGroup.tsx
  components/portfolio/PortfolioIdentity.tsx
  components/ui/SubTabsList.tsx
  lib/hooks/queries/useBadges.ts
  pages/avatar/[address].tsx
  pages/portfolio/[address].tsx
  tailwind.config.js
Labels: review needed

#1003 657: Display total cost of position on portfolio page
  components/portfolio/MarketPositions.tsx
  lib/hooks/queries/usePortfolioPositions.ts
Labels: review needed

#1264 Currency filtering
  components/markets/market-filter/DropDownSelect.tsx
  components/markets/market-filter/index.tsx
  components/markets/market-filter/mobile-dialog/FilterDetails.tsx
  lib/constants/foreign-asset.ts
  lib/constants/index.ts
  lib/constants/market-filter.ts
  lib/hooks/queries/useAssetUsdPrice.ts
  lib/hooks/queries/useCurrencyBalances.ts
Labels: review needed

#1275 Fix some strictNullCheck errors
  components/account/AccountButton.tsx
  components/account/AccountSelect.tsx
  components/account/OnboardingModal.tsx
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/context/ContentDimensionsContext.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/MarketLiquiditySection.tsx
  components/liquidity/PoolSettings.tsx
  components/liquidity/PoolTable.tsx
  components/markets/MarketChart.tsx
  components/ui/TimeSeriesChart.tsx
  components/ui/Toggle.tsx
  components/ui/TransactionButton.tsx
  lib/constants/foreign-asset.ts
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useAssetMetadata.ts
  lib/hooks/queries/useAssetUsdPrice.ts
  lib/hooks/queries/useBadges.ts
  lib/hooks/queries/useBalance.ts
  lib/hooks/queries/useExtrinsicFee.ts
  lib/hooks/queries/useIdentity.ts
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/queries/useMarket.ts
  lib/hooks/queries/useMarketStage.ts
  lib/hooks/queries/usePool.ts
  lib/hooks/queries/usePoolBaseBalance.ts
  lib/hooks/queries/usePoolBaseBalances.ts
  lib/hooks/queries/usePoolLiquidity.ts
  lib/hooks/queries/useTradeHistory.ts
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/queries/useZtgBalance.ts
  lib/hooks/useCrossChainExtrinsic.ts
  lib/hooks/useExtrinsic.ts
  lib/state/cross-chain.ts
  lib/state/notifications.ts
  lib/util/tx.ts
  pages/404.tsx
  pages/api/og/generate.tsx
  pages/markets/[marketid].tsx
  pages/portfolio/[address].tsx
Labels: review needed

#1287 Refactor all secondary buttons to the same component + add disabled styling
  components/assets/AssetActionButtons/AssetTradingButtons.tsx
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/liquidity/MarketLiquiditySection.tsx
  components/markets/BuySellFullSetsButton.tsx
  components/markets/ScalarPriceRange.tsx
  components/portfolio/DepositButton.tsx
  components/portfolio/WithdrawButton.tsx
  components/ui/SecondaryButton.tsx
  lib/util/format-compact.ts
  lib/util/get-scalar-outcome.ts
  lib/util/index.ts
  pages/api/og/generate.tsx
Labels: review needed
