Repository zeitgeistpm/ui, pull requests merged in 2023-01, with the labels that each got.

#507 add playwright and some tests
  .github/workflows/playwright.yml
  .github/workflows/test.yml
  .gitignore
  components/markets/MarketsList.tsx
  components/markets/market-card/index.tsx
  components/ui/Table.tsx
  e2e/errors.spec.ts
  e2e/index.spec.ts
  e2e/lib/test.ts
  jest.config.js
  package.json
  pages/index.tsx
  pages/liquidity/index.tsx
  playwright.config.ts
  yarn.lock
Labels: review needed

#541 Newest markets + styling tweeks
  components/markets/MarketScroll.tsx
  components/markets/market-card/overlay-categories.tsx
  components/markets/market-filter/active-filters.tsx
  components/markets/market-filter/index.tsx
  lib/constants/market-filter.ts
  lib/gql/newest-markets.ts
  pages/markets/index.tsx
Labels: review needed

#543 Remove display of authorized address
  components/markets/MarketAddresses.tsx
  pages/markets/[marketid].tsx
Labels: review needed

#564 Update helper scripts + fixes
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/markets/MarketAssetDetails.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  pages/create.tsx
  scripts/createDummyMarkets.ts
  scripts/mts/marketsFiltering.mts
  scripts/mts/tsconfig.json
Labels: review needed

#570 fix for #498 - resolved outcome not showing correctly for scalar outcomes
  components/markets/MarketAssetDetails.tsx
  lib/stores/MarketStore.ts
  pages/markets/[marketid].tsx
Labels: review needed

#577 Hide court when NEXT_PUBLIC_SHOW_COURT is false
  components/menu/index.tsx
Labels: review needed

#578 Revert to using old sdk market extrinsic for buy / sell complete sets
  components/markets/BuyFullSetModal.tsx
  components/markets/SellFullSetModal.tsx
Labels: review needed

#552 Use native scroll and hide overflow on MarketScroll
  components/markets/MarketScroll.tsx
  components/markets/market-card/index.tsx
Labels: review needed

#584 stricter file type check when adding market image
  components/create/MarketSlugField.tsx
  lib/util/index.ts
  pages/create.tsx
Labels: review needed

#574 Trade sharing on twitter
  components/markets/LiquidityPill.tsx
  components/markets/TradeResult.tsx
Labels: review needed

#590 Update scalar bounds to match Subsquid
  lib/util/assets.ts
Labels: review needed

#588 Update trending markets to display the most traded pools for the week
  lib/gql/trending-markets.ts
Labels: review needed

#544 New popular categories
  components/front-page/PopularCategories.tsx
  lib/gql/popular-categories.ts
  pages/index-new.tsx
  pages/index.tsx
  public/category/crypto.png
  public/category/esports.png
  public/category/politics.png
  public/category/science.png
  public/category/sports.png
  public/category/tech.png
  public/topics/crypto.png
  public/topics/governance.png
  public/topics/politics.png
  public/topics/sports.png
Labels: review needed

#591 #529 grace period compensation
  components/assets/AssetActionButtons/index.tsx
  lib/gql/markets-list/outcomes-for-markets.ts
  lib/hooks/queries/useMarketStage.ts
  package.json
  yarn.lock
Labels: bug, review needed

#594 Hide losing outcomes from portfolio
  pages/portfolio/[address].tsx
Labels: review needed

#572 Scalar resolved prices
  components/markets/BuyFullSetModal.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/ScalarPriceRange.tsx
  components/markets/SellFullSetModal.tsx
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/math.ts
  lib/util/calc-scalar-winnings.ts
  lib/util/pool.ts
  pages/markets/[marketid].tsx
Labels: review needed

#593 #529 implement new market timer
  components/markets/MarketTimer.tsx
  pages/markets/[marketid].tsx
Labels: refactor, review needed, design

#624 Learn section copy changes
  components/front-page/LearnSection.tsx
Labels: review needed

#621 Subscribe balance events
  layouts/DefaultLayout.tsx
  lib/gql/markets.ts
  lib/hooks/queries/useAccountAssetBalances.ts
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useMarket24hrPriceChanges.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/useZtgBalance.ts
  lib/hooks/useSubscribeBlockEvents.ts
  pages/markets/[marketid].tsx
Labels: review needed

#626 fix redeem values on portfolio and notification message
  components/assets/AssetActionButtons/RedeemButton.tsx
  pages/portfolio/[address].tsx
Labels: review needed

#629 Adjust table styling
  components/markets/MarketAssetDetails.tsx
  components/ui/Table.tsx
  styles/index.css
Labels: review needed

#627 Refactor market prices calculation for reuse
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/util/calc-resolved-market-prices.ts
Labels: review needed

#633 Fix winning outcome lookup
  components/markets/MarketAssetDetails.tsx
  lib/hooks/queries/useMarket24hrPriceChanges.ts
Labels: review needed

#632 Upgrade sdk to support new runtime
  components/drawer/RightDrawer.tsx
  components/outcomes/DisputeBox.tsx
  components/outcomes/RedeemBox.tsx
  components/outcomes/ReportBox.tsx
  lib/stores/MarketStore.ts
  lib/stores/Store.ts
  package.json
  pages/create.tsx
  yarn.lock
Labels: review needed
