Repository zeitgeistpm/ui, pull requests merged in 2023-02, with the labels that each got.

#651 Use classname to support other browsers
  components/ui/PercentageChange.tsx
Labels: review needed

#620 Implement portfolio breakdown
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/FullSetButtons.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/MarketsList.tsx
  components/markets/SellFullSetModal.tsx
  components/portfolio/Breakdown.tsx
  components/portfolio/MarketPositions.tsx
  components/ui/Footer.tsx
  components/ui/Table.tsx
  layouts/DefaultLayout.tsx
  lib/hooks/queries/useAccountAssetBalances.ts
  lib/hooks/queries/useAccountTokenPositions.ts
  lib/hooks/queries/useAssetsPriceHistory.ts
  lib/hooks/queries/useChainTime.ts
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/queries/useMarket.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/useMarketStage.ts
  lib/hooks/queries/useMarketsByIds.ts
  lib/hooks/queries/usePoolAccountIds.ts
  lib/hooks/queries/usePoolZtgBalance.ts
  lib/hooks/queries/usePoolsByIds.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useTotalIssuanceForPools.ts
  lib/hooks/queries/useZtgInfo.ts
  lib/util/index.ts
  package.json
  pages/markets/[marketid].tsx
  pages/portfolio/[address].tsx
  styles/index.css
  tailwind.config.js
  yarn.lock
Labels: review needed

#636 Transaction history
  components/portfolio/MarketPositions.tsx
  components/portfolio/TransactionHistoryTable.tsx
  lib/hooks/queries/useTransactionHistory.ts
  pages/portfolio/[address].tsx
Labels: review needed

#649 Recalculate prices when basePoolBalance or balances change
  lib/hooks/queries/useMarketSpotPrices.ts
Labels: review needed

#637 604 update cards
  components/markets/MarketsList.tsx
  components/markets/_MarketScroll.tsx
  components/markets/market-card/_index.tsx
  components/markets/market-card/index.tsx
  components/markets/market-card/overlay-categories.tsx
  components/markets/market-card/overlay.tsx
  components/ui/MarketImage.tsx
  lib/gql/featured-markets.ts
  lib/gql/markets.ts
  lib/gql/newest-markets.ts
  lib/gql/trending-markets.ts
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/util/assets.ts
  tailwind.config.js
Labels: review needed

#652 quickfix inability to create scalar date markets
  pages/create.tsx
Labels: review needed

#642 Display reject reason + SDK upgrade
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/MarketTimer.tsx
  components/markets/market-card/overlay-categories.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  lib/hooks/queries/useAccountAssetBalances.ts
  lib/hooks/queries/useAccountBalanceHistory.ts
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useAccountTokenPositions.ts
  lib/hooks/queries/useIdentity.ts
  lib/hooks/queries/useMarket.ts
  lib/hooks/queries/useMarketDeadlineConstants.ts
  lib/hooks/queries/useMarketDisputes.ts
  lib/hooks/queries/useMarketIsTradingEnabled.ts
  lib/hooks/queries/useMarketStatusCount.ts
  lib/hooks/queries/usePoolAccountIds.ts
  lib/hooks/queries/usePoolZtgBalance.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useTotalIssuanceForPools.ts
  lib/hooks/queries/useTransactionHistory.ts
  lib/hooks/queries/useZtgBalance.ts
  lib/hooks/useSubscribeBlockEvents.ts
  lib/state/tradeslip/tradeslipItemsState.ts
  lib/state/tradeslip/tradeslipTotalState.ts
  lib/util/assets.ts
  package.json
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
  yarn.lock
Labels: review needed

#654 Fix ztg prices
  .github/workflows/playwright.yml
  components/drawer/RightDrawer.tsx
  components/ui/Table.tsx
  lib/hooks/queries/useZtgInfo.ts
  lib/stores/Store.ts
  lib/util/fetch-ztg-price.ts
  pages/liquidity/[poolid].tsx
Labels: needs-conflicts-resolved

#671 Handle markets that don't have a pool after active status has passed
  components/markets/MarketAssetDetails.tsx
  components/markets/PoolDeployer.tsx
Labels: bug, review needed

#675 Update banner image (main)
  pages/index.tsx
  public/carousel/superbowl.png
Labels: review needed

#674 Update banner image
  pages/index.tsx
  public/carousel/superbowl.png
Labels: review needed

#665 Portfolio bonds
  components/portfolio/BondsTable.tsx
  components/portfolio/Breakdown.tsx
  components/portfolio/MarketPositionHeader.tsx
  components/portfolio/MarketPositions.tsx
  lib/hooks/queries/useAccountBonds.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useZtgInfo.ts
  pages/portfolio/[address].tsx
Labels: review needed

#546 Social Media open graph image generation
  components/meta/MarketMeta.tsx
  components/meta/OgHead.tsx
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/util/assets.ts
  next.config.js
  package.json
  pages/_document.tsx
  pages/api/og/[marketId].ts
  pages/api/og/generate.tsx
  pages/badges.tsx
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
  public/fonts/inter/static/Inter-Black.ttf
  public/fonts/inter/static/Inter-Bold.ttf
  public/fonts/inter/static/Inter-ExtraBold.ttf
  public/fonts/inter/static/Inter-ExtraLight.ttf
  public/fonts/inter/static/Inter-Light.ttf
  public/fonts/inter/static/Inter-Medium.ttf
  public/fonts/inter/static/Inter-Regular.ttf
  public/fonts/inter/static/Inter-SemiBold.ttf
  public/fonts/inter/static/Inter-Thin.ttf
  public/fonts/inter/variable.ttf
  public/og/bg1.png
  public/og/zeitgeist_badge.png
  yarn.lock
Labels: work in progress, review needed

#599 512 update home page
  components/drawer/Drawer.tsx
  components/drawer/LeftDrawer.tsx
  components/drawer/RightDrawer.tsx
  components/front-page/LearnSection.tsx
  components/hero-slider/HeroControls.tsx
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.tsx
  components/hero-slider/slider-types.ts
  components/hero-slider/slides-data.ts
  components/icons/ZeitgeistIcon.tsx
  components/markets/MarketScroll.tsx
  components/markets/market-card/index.tsx
  components/menu/MobileMenu.tsx
  components/top-bar/index.tsx
  components/ui/Footer.tsx
  components/ui/_Footer.tsx
  layouts/DefaultLayout.tsx
  layouts/DemoLayout.tsx
  lib/stores/Store.ts
  pages/_app.tsx
  pages/index-new.tsx
  pages/index.tsx
  public/footer-image.png
  styles/index.css
Labels: design

#694 fix use marketType prop to check if scalar market
  components/markets/market-card/index.tsx
Labels: bug, review needed

#704 Fix: add number formatting for volume on market cards
  components/markets/market-card/index.tsx
Labels: bug, review needed

#678 Fix salar date markets reporting, disputing and display of values
  components/markets/MarketAssetDetails.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  components/ui/inputs.tsx
  lib/stores/MarketStore.ts
  package.json
  pages/create.tsx
  yarn.lock
Labels: review needed

#703 Change hero banner + minor changes
  components/front-page/LearnSection.tsx
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.tsx
  components/hero-slider/slides-data.ts
  public/carousel/slide-1.jpeg
  public/carousel/slide-2.jpeg
  public/carousel/slide-3.jpeg
  public/carousel/slide-4.jpeg
  styles/index.css
Labels: review needed

#707 Misc styling and visual bugs
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/liquidity/PoolSettings.tsx
  components/liquidity/PoolTable.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/market-filter/active-filters.tsx
  components/markets/market-filter/index.tsx
  components/portfolio/Breakdown.tsx
  components/portfolio/MarketPositionHeader.tsx
  components/portfolio/MarketPositions.tsx
  components/ui/Table.tsx
  lib/hooks/queries/usePortfolioPositions.ts
  pages/markets/[marketid].tsx
  pages/portfolio/[address].tsx
  tailwind.config.js
Labels: review needed

#713 Fix: Market card incorrectly states "No liquidity"
  components/markets/MarketsList.tsx
  components/markets/market-card/index.tsx
  lib/gql/featured-markets.ts
  lib/gql/newest-markets.ts
  lib/gql/trending-markets.ts
Labels: bug, review needed

#719 Newest markets displaying resolved markets
  lib/gql/newest-markets.ts
Labels: review needed

#736 SDK 2.20.0
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/portfolio/MarketPositions.tsx
  components/trade-slip/TradeSlipItem.tsx
  lib/hooks/queries/useAccountAssetBalances.ts
  lib/hooks/queries/useAccountPoolAssetBalances.ts
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/useMarketStatusCount.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useZtgBalance.ts
  lib/hooks/useSdkv2.ts
  lib/state/tradeslip/tradeslipItemsState.ts
  lib/util/assets.ts
  package.json
  pages/liquidity/[poolid].tsx
  pages/liquidity/index.tsx
  yarn.lock
Labels: review needed

#740 Add banner to slider
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.tsx
  components/hero-slider/slider-types.ts
  components/hero-slider/slides-data.ts
  public/carousel/spaceship_banner_ai.png
Labels: review needed

#745 Remove market metadata from pool page
  pages/liquidity/[poolid].tsx
Labels: bug

#702 Liquidity modal
  components/create/OutcomesField.tsx
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/ManageLiquidityButton.tsx
  components/ui/FormTransactionButton.tsx
  lib/hooks/queries/useTotalIssuanceForPools.ts
  lib/hooks/useExtrinsic.ts
  lib/types/create-market.ts
  pages/markets/[marketid].tsx
Labels: review needed

#734 Static side bar
  components/account/AccountButton.tsx
  components/drawer/LeftDrawer.tsx
  components/drawer/RightDrawer.tsx
  components/hero-slider/HeroControls.tsx
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/slides-data.ts
  components/menu/MenuItem.tsx
  components/menu/MobileMenu.tsx
  components/menu/index.tsx
  components/top-bar/MarketSearch.tsx
  components/top-bar/index.tsx
  components/ui/_Footer.tsx
  layouts/DefaultLayout.tsx
  pages/markets/index.tsx
  styles/index.css
  tailwind.config.js
Labels: needs-conflicts-resolved
