Repository zeitgeistpm/ui, pull requests merged in 2023-04, with the labels that each got.

#918 Home page updates
  components/account/AccountButton.tsx
  components/front-page/LearnSection.tsx
  components/front-page/PopularCategories.tsx
  components/markets/MarketScroll.tsx
  components/menu/MenuLogo.tsx
  components/menu/MobileMenu.tsx
  components/menu/index.tsx
  components/ui/HorizontalScroll.tsx
  pages/index.tsx
Labels: review needed

#967 Remove settings from left nav
  components/menu/navigation-items.ts
  lib/types/navigation.ts
Labels: review needed

#961 Add new ws endpoint + styling
  components/markets/MarketHeader.tsx
  components/markets/MarketTimer.tsx
  components/ui/TimeSeriesChart.tsx
  lib/constants/index.ts
Labels: review needed

#970 Disable redeem button if value is zero + Remove PoolStore
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/index.tsx
  lib/hooks/queries/usePoolLiquidity.ts
  lib/stores/MarketsStore.ts
  lib/stores/PoolsStore.ts
  lib/stores/Store.ts
  pages/markets/[marketid].tsx
Labels: review needed

#973 Card spacing
  components/markets/market-card/index.tsx
Labels: review needed

#974 Fix card widths on initial load
  components/markets/MarketScroll.tsx
  components/markets/market-card/index.tsx
  components/ui/Table.tsx
  package.json
  tailwind.config.js
  yarn.lock
Labels: review needed

#1010 Update pricehistory resolver call
  components/markets/MarketChart.tsx
  components/ui/TimeFilters.tsx
  lib/hooks/queries/useMarketPriceHistory.ts
  pages/markets/[marketid].tsx
Labels: review needed

#989 Price in $ shows NaN until ZTG price is fetched
  components/ui/Table.tsx
Labels: review needed

#976 Remove store sdk
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/FullSetButtons.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/SellFullSetModal.tsx
  lib/hooks/account.tsx
  package.json
  pages/avatar/[address].tsx
  pages/settings.tsx
  yarn.lock
Labels: review needed

#1008 Resolved withdraw liquidity
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/PoolTable.tsx
Labels: review needed

#994 Add categorical dispute confirmation
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/markets/MarketAssetDetails.tsx
  components/outcomes/CategoricalDisputeBox.tsx
  components/ui/TimeSeriesChart.tsx
Labels: review needed

#1018 Add link to hydra dx
  components/account/OnboardingModal.tsx
Labels: review needed

#1005 #940 refactor wallets store to use jotai
  components/account/AccountButton.tsx
  components/account/AccountModalContent.tsx
  components/account/AccountSelect.tsx
  components/account/OnboardingModal.tsx
  components/account/WalletDisconnector.tsx
  components/account/WalletSelect.tsx
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/liquidity/LiquidityModal.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/PoolDeployer.tsx
  components/markets/SellFullSetModal.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  components/portfolio/MarketPositions.tsx
  components/trade-form/index.tsx
  components/ui/FormTransactionButton.tsx
  components/ui/TransactionButton.tsx
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/useExtrinsic.ts
  lib/hooks/usePrevious.ts
  lib/hooks/useSdkv2.ts
  lib/hooks/useUserLocation.ts
  lib/query-client.ts
  lib/state/util/persistent-atom.ts
  lib/state/wallet.ts
  lib/stores/Store.ts
  lib/stores/wallets/index.ts
  lib/types/deep-readonly.ts
  lib/wallets/base-dotsama-wallet/index.ts
  lib/wallets/errors/AuthError.tsx
  lib/wallets/errors/BaseWalletError.tsx
  lib/wallets/polkadotjs-wallet/index.ts
  lib/wallets/subwallet/index.ts
  lib/wallets/talisman-wallet/index.ts
  lib/wallets/types.ts
  package.json
  pages/_app.tsx
  pages/avatar/[address].tsx
  pages/avatar/index.tsx
  pages/create.tsx
  pages/portfolio/index.tsx
  pages/settings.tsx
  yarn.lock
Labels: review needed

#1050 Category anchor link
  components/front-page/PopularCategories.tsx
  components/markets/MarketsList.tsx
Labels: review needed

#1063 Fix app crashing when viewing pool table too quickly
  components/liquidity/PoolTable.tsx
Labels: bug, review needed

#1069 Add ability to collapse table columns if there is overflow
  components/assets/AssetActionButtons/TradeButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/markets/MarketAssetDetails.tsx
  components/ui/Table.tsx
Labels: review needed

#1071 Remove gql client from store and use sdkv2 indexer where it was used.
  lib/constants/index.ts
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/queries/useMarketsStats.ts
  lib/stores/Store.ts
  pages/create.tsx
Labels: review needed

#1074 Pull out chain constants(store.config) loading to react-query hook.
  components/account/AccountButton.tsx
  components/create/OutcomesField.tsx
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/PoolSettings.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/MarketCostModal.tsx
  components/markets/PoolDeployer.tsx
  components/markets/SellFullSetModal.tsx
  components/outcomes/CategoricalDisputeBox.tsx
  components/outcomes/ScalarDisputeBox.tsx
  lib/hooks/queries/useChainConstants.ts
  lib/hooks/queries/useMarket24hrPriceChanges.ts
  lib/stores/Store.ts
  pages/create.tsx
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
  pages/settings.tsx
Labels: refactor, mobx-refactor

#1090 Fix initial wallet enabling
  lib/wallets/base-dotsama-wallet/index.ts
Labels: bug

#1089 Multi asset support 1
  components/account/AccountButton.tsx
  components/account/AccountModalContent.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/PoolSettings.tsx
  components/liquidity/PoolTable.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/PoolDeployer.tsx
  components/portfolio/BondsTable.tsx
  components/portfolio/TransactionHistoryTable.tsx
  components/ui/Table.tsx
  lib/constants/foreign-asset.ts
  lib/hooks/queries/useAssetUsdPrice.ts
  lib/hooks/queries/useBalance.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/usePoolBaseBalance.ts
  lib/hooks/queries/usePoolLiquidity.ts
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/queries/useZtgBalance.ts
  lib/hooks/useSubscribeBlockEvents.ts
  lib/util/index.ts
  package.json
  pages/liquidity/[poolid].tsx
  pages/markets/[marketid].tsx
  public/currencies/dot.png
  yarn.lock
Labels: review needed

#1097 Prevent body width changing on mobile menu open
  components/menu/index.tsx
Labels: review needed

#1104 Open external banner links in new tab
  components/hero-slider/HeroControls.tsx
  components/hero-slider/HeroSlide.tsx
  components/meta/MarketMeta.tsx
  lib/util/is-current-origin.ts
Labels: enhancement, review needed

#1102 Multi asset 2
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/PoolTable.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/MarketChart.tsx
  components/markets/MarketsList.tsx
  components/markets/SellFullSetModal.tsx
  components/markets/market-card/index.tsx
  components/portfolio/TransactionHistoryTable.tsx
  components/trade-form/index.tsx
  components/ui/Table.tsx
  components/ui/TimeSeriesChart.tsx
  lib/constants/foreign-asset.ts
  lib/gql/featured-markets.ts
  lib/gql/newest-markets.ts
  lib/gql/trending-markets.ts
  lib/hooks/queries/useAssetMetadata.ts
  lib/hooks/queries/useAssetUsdPrice.ts
  lib/hooks/queries/useChainConstants.ts
  lib/hooks/queries/useMarket.ts
  lib/hooks/queries/usePoolBaseBalance.ts
  lib/hooks/queries/usePoolBaseBalances.ts
  lib/hooks/queries/usePoolLiquidity.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/queries/useZtgInfo.ts
  lib/hooks/queries/useZtgPrice.ts
  lib/hooks/trade.tsx
  package.json
  pages/liquidity/[poolid].tsx
  pages/liquidity/index.tsx
  pages/markets/[marketid].tsx
  pages/portfolio/[address].tsx
  yarn.lock
Labels: review needed

#1057 Disputed markets
  components/markets/MarketAssetDetails.tsx
  components/markets/MarketHeader.tsx
  components/markets/MarketTimer.tsx
  components/markets/ScalarPriceRange.tsx
  lib/gql/markets.ts
  lib/hooks/queries/useMarketDisputes.ts
  lib/util/assets.ts
  lib/util/market-status-details.ts
  pages/markets/[marketid].tsx
  tailwind.config.js
Labels: review needed

#1115 Image generation fixes/ adjustment
  pages/api/og/[marketId].ts
  pages/api/og/generate.tsx
Labels: review needed

#1120 Fix: mobile menu bg
  components/menu/MobileMenu.tsx
Labels: review needed

#1116 Fix hydra dx link
  components/account/OnboardingModal.tsx
Labels: review needed

#1111 Refactor transaction error handling
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  lib/hooks/useExtrinsic.ts
  lib/stores/Store.ts
  lib/util/tx.ts
  pages/avatar/[address].tsx
  pages/create.tsx
Labels: review needed

#1129 Improve banner slide animation
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.module.css
  components/hero-slider/HeroSlider.tsx
  e2e/index.spec.ts
  e2e/lib/index.page.ts
Labels: review needed
