Repository zeitgeistpm/ui, pull requests merged in 2023-07, with the labels that each got.

#1479 Fix Rococo account structure error
  lib/constants/chains.ts
Labels: review needed

#1470 Fix: card heights and padding
  components/markets/market-card/index.tsx
Labels: review needed

#1483 Fix withdraw extrinsic
  components/portfolio/WithdrawButton.tsx
Labels: review needed

#1491 Fix categorical market redeems
  components/assets/AssetActionButtons/RedeemButton.tsx
Labels: review needed

#1472 More null checks
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.tsx
  components/markets/PromotionCallout.tsx
  components/markets/market-card/index.tsx
  components/portfolio/DepositButton.tsx
  components/ui/Table.tsx
  components/ui/inputs.tsx
  lib/cms/get-banners.ts
  lib/cms/get-promoted-markets.ts
  lib/hooks/useCrossChainExtrinsic.ts
  lib/state/cross-chain.ts
  lib/state/market-creation/types/validation.ts
  lib/state/wallet.ts
  lib/util/calc-resolved-market-prices.ts
  lib/util/is-current-origin.ts
  lib/util/normalize.ts
  lib/wallets/base-dotsama-wallet/index.ts
  pages/_app.tsx
  pages/api/og/[marketId].ts
  pages/api/og/generate.tsx
  pages/badges.tsx
  pages/markets/[marketid].tsx
  pages/settings.tsx
Labels: review needed

#1496 Use base asset symbol
  components/assets/AssetActionButtons/RedeemButton.tsx
  lib/util/parse-asset-id.ts
Labels: review needed

#1493 Consolidate components to use useExtrinsic
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
Labels: review needed

#1475 Handle delay when loading portfolio
  components/portfolio/CurrenciesTable.tsx
  layouts/PortfolioLayout.tsx
Labels: review needed

#1465 #1419 base asset pool settings
  components/create/editor/Editor.tsx
  components/create/editor/inputs/Liquidity.tsx
  components/liquidity/MarketLiquiditySection.tsx
  components/markets/PoolDeployer.tsx
  lib/hooks/queries/useMarket.ts
  lib/hooks/useExtrinsic.ts
  package.json
  pages/markets/[marketid].tsx
  yarn.lock
Labels: bug, enhancement

#1494 Deposit adjustments
  components/portfolio/DepositButton.tsx
Labels: review needed

#1503 #670 proxy calls
  .vscode/settings.json
  components/account/AccountButton.tsx
  components/account/AccountModalContent.tsx
  components/account/AccountSelect.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/create/editor/Publishing.tsx
  components/create/editor/inputs/Oracle.tsx
  components/liquidity/LiquidityModal.tsx
  components/markets/BuyFullSetForm.tsx
  components/markets/PoolDeployer.tsx
  components/markets/SellFullSetForm.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  components/portfolio/DepositButton.tsx
  components/portfolio/MarketPositions.tsx
  components/portfolio/PortfolioIdentity.tsx
  components/portfolio/WithdrawButton.tsx
  components/trade-form/index.tsx
  components/ui/CopyIcon.tsx
  layouts/PortfolioLayout.tsx
  lib/hooks/queries/useExtrinsicFee.ts
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/useCrossChainExtrinsic.ts
  lib/hooks/useExtrinsic.ts
  lib/state/market-creation/types/form.ts
  lib/state/wallet.ts
  pages/avatar/[address].tsx
  pages/settings.tsx
Labels: work in progress, review needed

#1501 Show Report/Resolution date
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/markets/MarketHeader.tsx
  lib/gql/markets.ts
  lib/util/estimate-market-resolution.ts
  pages/markets/[marketid].tsx
Labels: review needed

#1526 Allow table data to be undefined to show skeletons
  components/markets/MarketAssetDetails.tsx
  components/portfolio/CurrenciesTable.tsx
  components/portfolio/TradeHistoryTable.tsx
  components/portfolio/TransactionHistoryTable.tsx
  components/ui/Table.tsx
Labels: review needed

#1313 Leaderboard
  components/menu/index.tsx
  lib/constants/foreign-asset.ts
  lib/util/calc-scalar-winnings.spec.ts
  lib/util/calc-scalar-winnings.ts
  package.json
  pages/leaderboard.tsx
  yarn.lock
Labels: review needed

#1565 New account structure
  components/liquidity/LiquidityModal.tsx
  components/liquidity/PoolTable.tsx
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/usePoolBaseBalance.ts
  lib/hooks/queries/usePoolLiquidity.ts
  package.json
  yarn.lock
Labels: review needed

#1559 Remove null chart values instead of setting to 0
  components/markets/MarketChart.tsx
Labels: review needed

#1566 Fix market page SSG
  components/markets/MarketHeader.tsx
  pages/markets/[marketid].tsx
Labels: review needed

#1549 Deposit form fixes/enhancements
  components/portfolio/DepositButton.tsx
  lib/hooks/queries/useCurrencyBalances.ts
Labels: review needed

#1580 Fix for account button dropdown not showing on mobile
  components/account/AccountButton.tsx
Labels: review needed

#1548 Trade feed
  components/front-page/LatestTrades.tsx
  components/front-page/PopularCategories.tsx
  components/portfolio/PortfolioIdentity.tsx
  lib/gql/market-header.ts
  lib/hooks/queries/useLatestTrades.tsx
  lib/hooks/queries/useTradeHistory.ts
  pages/index.tsx
Labels: review needed

#1569 SSG market cards
  components/markets/MarketsList.tsx
  components/markets/market-card/index.tsx
  components/ui/Avatar.tsx
  lib/gql/display-name.ts
  lib/gql/featured-markets.ts
  lib/gql/trending-markets.ts
  pages/index.tsx
  pages/leaderboard.tsx
Labels: review needed

#1584 Try improving avatar rendering speed
  components/ui/Avatar.tsx
  lib/hooks/queries/useAvatarParts.ts
  package.json
  yarn.lock
Labels: work in progress

#1582 Better mobile layout for account select modal
  components/account/AccountSelect.tsx
  components/account/AccountSelectOption.tsx
  components/account/AccountSelectValue.tsx
Labels: review needed

#1594 SSG avatar
  lib/hooks/queries/useAvatarParts.ts
  lib/util/create-avatar-sdk.ts
  pages/_app.tsx
  pages/leaderboard.tsx
Labels: review needed

#1605 Change scalar order to match weights
  lib/state/market-creation/util/tickers.ts
Labels: review needed

#1600 Fix market report not being displayed
  lib/util/market-status-details.ts
Labels: review needed

#1567 #1528 tx history subscan links
  components/portfolio/TradeHistoryTable.tsx
  components/portfolio/TransactionHistoryTable.tsx
  lib/hooks/queries/useTradeHistory.ts
  lib/hooks/queries/useTransactionHistory.ts
  lib/state/market-creation/util/tickers.ts
  package.json
  yarn.lock
Labels: review needed
