Repository zeitgeistpm/ui, pull requests merged in 2023-06, with the labels that each got.

#1307 Format scalar dates
  pages/markets/[marketid].tsx
Labels: review needed

#1157 Scalar util fn for displaying outcomes
  components/markets/MarketHeader.tsx
  components/markets/ScalarPriceRange.tsx
  lib/util/format-scalar-outcome.ts
  lib/util/market-status-details.ts
Labels: review needed

#1321 Use correct network fee units
  components/trade-form/index.tsx
Labels: review needed

#1297 Hide dust balances within portfolio
  components/portfolio/MarketPositions.tsx
  lib/constants/index.ts
Labels: review needed

#1329 Filter all base assets, not just ZTG
  lib/hooks/queries/useAccountPoolAssetBalances.ts
Labels: review needed

#1323 Strict null checks
  components/account/AccountButton.tsx
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/context/ContentDimensionsContext.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/PoolTable.tsx
  components/markets/BuyFullSetForm.tsx
  components/markets/BuySellFullSetsButton.tsx
  components/markets/MarketAddresses.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/MarketHeader.tsx
  components/markets/SellFullSetForm.tsx
  components/markets/market-card/index.tsx
  components/menu/MenuItem.tsx
  components/menu/MenuLogo.tsx
  components/onboarding/Onboarding.tsx
  components/ui/Table.tsx
  components/ui/TimeSeriesChart.tsx
  layouts/DefaultLayout.tsx
  lib/constants/index.ts
  lib/gql/markets-list/outcomes-for-markets.ts
  lib/hooks/queries/useAccountTokenPositions.ts
  lib/hooks/queries/useChainConstants.ts
  lib/hooks/queries/useCurrencyBalances.ts
  lib/hooks/queries/useIdentity.ts
  lib/hooks/queries/useInfinitePoolsList.ts
  lib/hooks/queries/useMarket24hrPriceChanges.ts
  lib/hooks/queries/useMarketSpotPrices.ts
  lib/hooks/queries/usePoolBaseBalance.ts
  lib/hooks/queries/usePoolLiquidity.ts
  lib/hooks/queries/usePrizePool.ts
  lib/types/user-identity.ts
  lib/util/parse-asset-id.ts
  pages/liquidity/[poolid].tsx
Labels: review needed

#1330 Profile tooltips
  components/portfolio/MarketPositions.tsx
  components/ui/InfoPopover.tsx
  components/ui/Table.tsx
Labels: review needed

#1359 Fee token amount validation
  components/portfolio/DepositButton.tsx
  components/portfolio/WithdrawButton.tsx
  components/trade-form/index.tsx
  components/ui/TransactionButton.tsx
  lib/hooks/queries/useExtrinsicFee.ts
Labels: review needed

#1372 Switch to V2
  components/portfolio/DepositButton.tsx
  lib/constants/chains.ts
Labels: review needed

#1401 Style tooltips on create page and tables according to designs
  components/create/editor/Editor.tsx
  components/create/editor/InfoPopover.tsx
  components/liquidity/PoolSettings.tsx
  components/ui/InfoPopover.tsx
  components/ui/Table.tsx
  tailwind.config.js
Labels: review needed

#1358 #1288 notifications restyle
  components/menu/index.tsx
  components/ui/Loader.tsx
  components/ui/NotificationCenter.tsx
  lib/state/notifications.ts
  package.json
  tailwind.config.js
  yarn.lock
Labels: work in progress, review needed

#1405 ED checks
  components/portfolio/CurrenciesTable.tsx
  components/portfolio/DepositButton.tsx
  components/portfolio/WithdrawButton.tsx
  lib/constants/chains.ts
  lib/hooks/queries/useCurrencyBalances.ts
  lib/hooks/useCrossChainExtrinsic.ts
Labels: review needed

#1378 Strict null 2
  components/create/editor/inputs/BlockPeriod.tsx
  components/markets/MarketScroll.tsx
  components/markets/MarketsList.tsx
  components/markets/PoolDeployer.tsx
  components/markets/ScalarPriceRange.tsx
  components/markets/market-card/context.ts
  components/markets/market-card/index.tsx
  components/meta/MarketMeta.tsx
  components/outcomes/ScalarReportBox.tsx
  components/portfolio/CurrenciesTable.tsx
  components/portfolio/TradeHistoryTable.tsx
  components/ui/NotificationCenter.tsx
  components/ui/ProgressReport/Countdown.tsx
  components/ui/ProgressReport/ProgressBar.tsx
  components/ui/ProgressReport/TimeLineEvent.tsx
  components/ui/ProgressReport/index.tsx
  components/ui/QuillEditor.tsx
  components/ui/RangeInput.tsx
  components/wizard/types.ts
Labels: review needed

#1406 Navigation restyle
  components/account/AccountButton.tsx
  components/markets/market-filter/index.tsx
  components/menu/MenuLogo.tsx
  components/menu/MobileMenu.tsx
  components/menu/SideMenu.tsx
  components/menu/index.tsx
  layouts/DefaultLayout.tsx
  styles/index.css
Labels: work in progress

#1449 Header changes
  components/account/AccountButton.tsx
  components/hero-slider/HeroSlider.tsx
  components/markets/MarketsList.tsx
  components/menu/index.tsx
  lib/gql/newest-markets.ts
  pages/markets/index.tsx
Labels: review needed

#1454 Display available balance
  lib/constants/chains.ts
  lib/hooks/queries/useBalance.ts
  lib/hooks/queries/useCurrencyBalances.ts
  lib/util/calc-free-balance.spec.ts
  lib/util/calc-free-balance.ts
Labels: review needed

#1456 #452 strict null 1
  components/assets/AssetActionButtons/index.tsx
  components/create/editor/Editor.tsx
  components/create/editor/inputs/BlockPeriod.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/TradeResult.tsx
  components/markets/market-filter/DropDownSelect.tsx
  components/markets/market-filter/MarketActiveFilters.tsx
  components/markets/market-filter/MarketFiltersContainer.tsx
  components/markets/market-filter/index.tsx
  components/portfolio/MarketPositions.tsx
  components/trade-form/index.tsx
  components/wizard/WizardStepper.tsx
  lib/hooks/queries/useAccountAssetBalances.ts
  lib/hooks/queries/useAccountBonds.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/hooks/queries/useTradeHistory.ts
  lib/hooks/queries/useZtgPrice.ts
  lib/hooks/trade.tsx
  pages/portfolio/[address].tsx
  tsconfig.json
Labels: work in progress, review needed

#1370 Updated cards
  components/markets/MarketHeader.tsx
  components/markets/MarketsList.tsx
  components/markets/ScalarPriceRange.tsx
  components/markets/market-card/index.tsx
  components/ui/Avatar.tsx
  lib/constants/foreign-asset.ts
  lib/gql/featured-markets.ts
  lib/gql/trending-markets.ts
  public/currencies/ztg.png
  public/icons/politics-cat-icon.svg
  public/icons/usdc-icon.svg
  public/icons/verified-icon.svg
  tailwind.config.js
Labels: review needed

#1270 Remove fees from spot price calculation
  components/trade-form/index.tsx
  lib/hooks/queries/useTradeItemState.ts
Labels: review needed

#1466 Delay cache invalidation to wait for indexer
  components/trade-form/index.tsx
  components/ui/NotificationCenter.tsx
  lib/hooks/queries/useAccountTokenPositions.ts
  lib/hooks/queries/usePortfolioPositions.ts
  lib/state/market-creation/types/validation.ts
  lib/util/await-indexer.ts
Labels: review needed

#1471 Fix polkadot balance loading
  lib/constants/chains.ts
Labels: review needed
