Repository zeitgeistpm/ui, pull requests merged in 2023-03, with the labels that each got.

#766 Use default description instead of market description
  components/meta/MarketMeta.tsx
  components/meta/OgHead.tsx
Labels: review needed

#775 Fix incorrect text
  components/markets/MarketHeader.tsx
Labels: bug

#735 Onboarding
  components/account/OnboardingModal.tsx
  package.json
  public/icons/polkadot-js.png
  public/icons/subwallet.png
  public/icons/talisman.png
  public/misc/face.png
  yarn.lock
Labels: review needed

#764 Add scalar range to market without liquidity
  components/markets/market-card/index.tsx
Labels: review needed

#782 Replace deprecated font lib with built in lib
  lib/util/fonts.ts
  package.json
  yarn.lock
Labels: review needed

#762 New modals
  components/assets/AssetActionButtons/TradeButton.tsx
  components/assets/AssetActionButtons/index.tsx
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/liquidity/LiquidityModal.tsx
  components/liquidity/ManageLiquidityButton.tsx
  components/liquidity/PoolTable.tsx
  components/markets/TradeResult.tsx
  components/portfolio/MarketPositions.tsx
  components/trade-form/TradeTab.tsx
  components/trade-form/index.tsx
  components/ui/Modal.tsx
  layouts/DefaultLayout.tsx
  lib/hooks/useExtrinsic.ts
  pages/_document.tsx
  pages/markets/[marketid].tsx
  styles/index.css
Labels: review needed

#781 Scroll management
  components/context/ContentDimensionsContext.tsx
  components/markets/MarketsList.tsx
  components/menu/MenuItem.tsx
  layouts/DefaultLayout.tsx
  lib/hooks/queries/useInfiniteMarkets.ts
  lib/hooks/useMarketsUrlQuery.ts
  pages/markets/index.tsx
Labels: review needed

#765 Markets filters styling
  components/front-page/PopularCategories.tsx
  components/markets/market-filter/MarketActiveFilters.tsx
  components/markets/market-filter/MarketFiltersContainer.tsx
  components/markets/market-filter/index.tsx
  lib/constants/market-filter.ts
  lib/constants/markets.ts
  lib/types/market-filter.ts
  package.json
  public/category/crypto.png
  public/category/dotsama.png
  public/category/e-sports.png
  public/category/esports.png
  public/category/news.png
  public/category/politics.png
  public/category/science.png
  public/category/sports.png
  public/category/tech.png
  public/category/technology.png
  public/category/zeitgeist.png
  public/currencies/ausd.jpg
  public/currencies/ztg.jpg
  tailwind.config.js
  yarn.lock
Labels: review needed

#795 Scalar price overlap
  components/markets/ScalarPriceRange.tsx
  pages/markets/[marketid].tsx
  styles/index.css
  styles/quill.css
Labels: review needed

#818 SDK 2.21.5
  package.json
  yarn.lock
Labels: review needed

#780 Use notion as cms
  .env.development
  .env.example
  components/hero-slider/HeroSlide.tsx
  components/hero-slider/HeroSlider.tsx
  components/hero-slider/slider-types.ts
  lib/cms/get-banners.ts
  lib/cms/get-featured-marketids.ts
  lib/gql/featured-markets.ts
  next.config.js
  package.json
  pages/api/revalidate.ts
  pages/index.tsx
  yarn.lock
Labels: review needed

#822 OG image styling
  pages/api/og/generate.tsx
  public/og/bg1.png
Labels: review needed

#828 Add simple migration banner
  .env.example
  components/top-bar/index.tsx
  layouts/DefaultLayout.tsx
  public/polkadot_icon.png
  styles/index.css
Labels: review needed

#825 Fix og image meta links to link to the correct domain and not build url
  .env.example
  components/meta/MarketMeta.tsx
Labels: review needed

#831 #729 new account drop down
  components/account/AccountButton.tsx
  components/account/OnboardingModal.tsx
  components/onboarding/Onboarding.tsx
  lib/state/onboarding.ts
  lib/state/tradeslip/items.ts
  pages/_app.tsx
  public/currencies/usdt.png
Labels: review needed

#850 Footer and container spacing
  components/hero-slider/HeroSlide.tsx
  components/ui/Footer.tsx
  styles/index.css
Labels: review needed

#796 Mobile menu
  components/account/AccountButton.tsx
  components/drawer/Drawer.tsx
  components/markets/market-card/index.tsx
  components/menu/MenuItem.tsx
  components/menu/MenuItemGroup.tsx
  components/menu/MenuLogo.tsx
  components/menu/MobileMenu.tsx
  components/menu/Navigation.tsx
  components/menu/SideMenu.tsx
  components/menu/index.tsx
  components/menu/navigation-items.ts
  components/menu/old/LocalizationSelect.tsx
  components/menu/old/MarketSearch.tsx
  components/menu/old/SubMenuItem.tsx
  components/menu/old/ThemeSwitch.tsx
  components/top-bar/index.tsx
  layouts/DefaultLayout.tsx
  lib/stores/NavigationStore.tsx
  pages/_app.tsx
Labels: review needed

#865 Add chart tool tip colour coding
  components/menu/MenuLogo.tsx
  components/ui/TimeSeriesChart.tsx
Labels: review needed

#856 Misc updates
  components/hero-slider/slider-controls.tsx
  components/markets/MarketTimer.tsx
  components/markets/market-card/index.tsx
  pages/index.tsx
  pages/markets/[marketid].tsx
Labels: review needed

#868 Fix market list shuffle
  components/markets/MarketsList.tsx
  components/markets/market-filter/index.tsx
  lib/hooks/queries/useInfiniteMarkets.ts
Labels: review needed

#896 Introduce ts-prune and remove some dead code.
  components/account/PortfolioCard.tsx
  components/account/RedeemAllButton.tsx
  components/assets/AssetActionButtons/BuySellButtons.tsx
  components/assets/AssetSelectButton.tsx
  components/assets/AssetSelectView.tsx
  components/context/ContentDimensionsContext.tsx
  components/drawer/Drawer.tsx
  components/drawer/RightDrawer.tsx
  components/exchange/ExchangeBox.tsx
  components/exchange/TypeSwitch.tsx
  components/liquidity/LiquidityCell.tsx
  components/liquidity/LiquidityPoolsBox.tsx
  components/markets/LiquidityPill.tsx
  components/markets/MarketSkeletons.tsx
  components/markets/SlippageInput.tsx
  components/markets/TrendingMarketCard.tsx
  components/markets/TrendingMarkets.tsx
  components/markets/featured-markets/FeaturedMarkets.tsx
  components/markets/market-card/context.ts
  components/menu/old/LocalizationSelect.tsx
  components/menu/old/MarketSearch.tsx
  components/menu/old/SubMenuItem.tsx
  components/menu/old/ThemeSwitch.tsx
  components/portfolio/MarketPositions.tsx
  components/trade-slip/TradeSlipItem.tsx
  components/trade-slip/index.tsx
  components/ui/AspectRatioImage.tsx
  components/ui/Button.tsx
  components/ui/Carousel.tsx
  components/ui/Countdown.tsx
  components/ui/GlitchImage.tsx
  components/ui/Image.tsx
  components/ui/Slider.tsx
  components/ui/Switch.tsx
  components/ui/Tabs.tsx
  components/ui/ToggleButton.tsx
  components/ui/inputs.tsx
  lib/constants/index.ts
  lib/gql/markets-list/types.ts
  lib/gql/pool.ts
  lib/hooks/index.ts
  lib/hooks/queries/useAccountBalanceHistory.ts
  lib/hooks/queries/useMarketStage.ts
  lib/hooks/usePoolsUrlQuery.ts
  lib/math.ts
  lib/state/tradeslip/items.ts
  lib/state/tradeslip/slippage.ts
  lib/state/tradeslip/tradeslipItemsState.ts
  lib/state/tradeslip/tradeslipTotalState.ts
  lib/stores/ExchangeStore.ts
  lib/stores/MarketStore.ts
  lib/stores/NavigationStore.tsx
  lib/stores/Store.ts
  lib/types/index.ts
  lib/util/index.ts
  lib/util/normalize.ts
  lib/util/pool.ts
  package.json
  yarn.lock
Labels: work in progress, refactor

#874 Portfolio and chart enhancements
  components/portfolio/BondsTable.tsx
  components/portfolio/Breakdown.tsx
  components/portfolio/EmptyPortfolio.tsx
  components/portfolio/TransactionHistoryTable.tsx
  components/ui/TimeSeriesChart.tsx
  lib/hooks/queries/useTransactionHistory.ts
  pages/portfolio/[address].tsx
  pages/portfolio/index.tsx
Labels: review needed

#878 Cards layout
  components/markets/MarketScroll.tsx
  components/markets/MarketsList.tsx
  lib/constants/breakpoints.ts
  lib/hooks/useWindowSize.ts
Labels: review needed

#841 change extrinsic type depending on trade state
  components/assets/AssetActionButtons/TradeButton.tsx
  components/trade-form/index.tsx
  layouts/DefaultLayout.tsx
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/trade.tsx
  lib/hooks/useExtrinsic.ts
  lib/hooks/useSubscribeBlockEvents.ts
Labels: review needed

#917 #891 'Liquidity only' filter not working
  lib/hooks/queries/useInfiniteMarkets.ts
Labels: review needed

#912 User store refactor
  components/account/AccountButton.tsx
  components/account/OnboardingModal.tsx
  components/account/WalletDisconnector.tsx
  components/account/WalletSelect.tsx
  components/icons/DiscordIcon.tsx
  components/icons/SubScanIcon.tsx
  components/icons/TwitterIcon.tsx
  components/icons/ZeitgeistIcon.tsx
  components/markets/MarketAddresses.tsx
  components/ui/Checkbox.tsx
  components/ui/FormTransactionButton.tsx
  components/ui/NotificationCenter.tsx
  components/ui/Select.tsx
  components/ui/TransactionButton.tsx
  lib/hooks/queries/useIdentity.ts
  lib/hooks/useLocalStorage.ts
  lib/hooks/useUserLocation.ts
  lib/stores/Store.ts
  lib/stores/UserStore.ts
  lib/stores/wallets/base-dotsama-wallet/index.ts
  lib/stores/wallets/errors/AuthError.tsx
  lib/stores/wallets/errors/BaseWalletError.tsx
  lib/stores/wallets/index.ts
  lib/stores/wallets/polkadotjs-wallet/index.ts
  lib/stores/wallets/subwallet/index.ts
  lib/stores/wallets/talisman-wallet/index.ts
  lib/stores/wallets/types.ts
  lib/types/index.ts
  lib/types/user-identity.ts
  pages/404.tsx
  pages/_app.tsx
  pages/avatar/[address].tsx
  pages/badges.tsx
  pages/portfolio/[address].tsx
Labels: work in progress, refactor

#932 Remove the asset page since its not used or in the new designs
  pages/asset.tsx
Labels: refactor

#861 Nova wallet integration
  components/account/AccountButton.tsx
  components/markets/FullSetButtons.tsx
  components/menu/MobileMenu.tsx
  components/menu/index.tsx
  components/ui/Table.tsx
  pages/liquidity/[poolid].tsx
Labels: review needed

#910 #887 Fix Modal Components Alignment
  components/trade-form/index.tsx
  components/ui/TransactionButton.tsx
  lib/hooks/queries/useInfiniteMarkets.ts
Labels: review needed

#937 #927 refactor notification state
  components/assets/AssetActionButtons/DisputeButton.tsx
  components/assets/AssetActionButtons/RedeemButton.tsx
  components/assets/AssetActionButtons/ReportButton.tsx
  components/liquidity/ExitPoolForm.tsx
  components/liquidity/JoinPoolForm.tsx
  components/markets/BuyFullSetModal.tsx
  components/markets/MarketAssetDetails.tsx
  components/markets/PoolDeployer.tsx
  components/markets/SellFullSetModal.tsx
  components/outcomes/ScalarDisputeBox.tsx
  components/outcomes/ScalarReportBox.tsx
  components/trade-form/index.tsx
  components/ui/Footer.tsx
  components/ui/NotificationCenter.tsx
  lib/hooks/queries/useTradeItemState.ts
  lib/hooks/trade.tsx
  lib/hooks/useExtrinsic.ts
  lib/state/notifications.ts
  lib/state/onboarding.ts
  lib/state/util/persistent-proxy.ts
  lib/stores/ExchangeStore.ts
  lib/stores/NavigationStore.tsx
  lib/stores/NotificationStore.ts
  lib/stores/Store.ts
  lib/util/generate-guid.ts
  lib/util/tx.ts
  package.json
  pages/avatar/[address].tsx
  pages/create.tsx
  pages/settings.tsx
  yarn.lock
Labels: work in progress, refactor, review needed

#946 #298 Display scalar or categorical on market page
  components/markets/MarketHeader.tsx
  components/markets/ScalarPriceRange.tsx
  components/markets/market-card/index.tsx
  lib/gql/featured-markets.ts
  lib/gql/markets.ts
  lib/gql/newest-markets.ts
  pages/markets/[marketid].tsx
Labels: review needed
